### PR TITLE
Upgrade faster-whisper 1.1.0rc0

### PR DESCRIPTION
**Pull request by makaveli10**
- Upgrade to faster_whisper==1.1.0rc0
- Enables whisper-turbo
- Minor fixes that improves punctatuations

### CODE REVIEW

**Comment by yatoooon** [comment]
hello  ,  Very happy to have updates but the transcription speed  is much slower this times

**Comment by makaveli10** [comment]
@yatoooon We didnt notice anything like that on our end, if you can share your setup, we can try and reproduce the issue.

**Comment by yatoooon** [comment]
same_output_threshold was 5 before, now it is 10.

**Comment by makaveli10** [comment]
yep, you can play with it, gave me better punctuations, shouldnt slow it down though.

**Pull request merged**
