### PR TITLE
Twilio Mock Data stream working

### PR DESCRIPTION
**Pull request by justinlevi**
1. Get the server running
$ `python ./run_server.py`

2. Get the client (streaming ws server) running
$ ` python ./run_client.py`

3. Send the mock audio stream to the client via:
$ `python ./twilio_mock_streaming_client.py`

image

### CODE REVIEW

**Review by zoq — COMMENTED** [review]
Thanks for another great contribution, testing it out and let you know if I encounter an issues.

**Review by zoq — COMMENTED** [review]
Thanks left some high level suggestions.

**Comment by justinlevi** [comment]
Appreciate the feedback. The more I think about this though, the more I'm unsure if this is the right approach. Feels a bit "hacky" to me to create a new websocket server in `run_client.py` that then sends data to the `whisper_live/client.py` and then the `whisper_live/server.py`

I did a bit of experimenting yesterday to modify the `whisper_live/server.py` to accept a twilio stream directly and I have it kind of working...

https://github.com/justinlevi/WhisperLive/commit/563ec07d4f9251e9bc56b60619f78024fc8413a7

The issue that I'm seeing is that the cleanup is called before the transcription is finished. From an architectural standpoint though I feel like this approach makes a lot more sense.

**Comment by yashpapa6969** [comment]
@justinlevi can you pleaseprovide code snippets for run_client.py and  twilio_mock_streaming_client.py

**Pull request closed without merging**
