### PR TITLE
Single model mode

### LINKED ISSUE #109: Individual model loaded for each client
First of all, thanks for the great project!

I've been playing around with the codebase recently and managed to deploy a server on a cloud instance quite easily thanks to the Docker images provided. However, it seems that a new model is loaded in memory for each websocket being opened, making GPU deployment hard to scale to 10+ clients on relatively small GPUs (8Go).

My understanding that a new model is loaded for each websocket opened comes form these code bits and the output of `nvidia-smi` for different number of clients connected:

https://github.com/collabora/WhisperLive/blob/0942dc2cfd8ba9fc0f21ecb623b73136526fb092/whisper_live/server.py#L252-L257

https://github.com/collabora/WhisperLive/blob/0942dc2cfd8ba9fc0f21ecb623b73136526fb092/whisper_live/transcriber.py#L132-L139

Am I correct that an invididual model is loaded for each client, even if two clients have the same model flavor?

If so, is that a design choice that was made or something that has been left for later? I'd be happy to work on a PR for that if such an addition was planned.

### PR DESCRIPTION
**Pull request by peldszus**
I added a mode in which all client connections use the same single model, instead of instantiating a new model for each connection. This only applies if a custom model has been specified at server start (i.e. a trt model or a custom fw model).

For this a new option has been added, defaulting to false, so that the current behaviour is not changed.

This partially resolves #109, but only for custom models. It does not apply for a fw-backend which dynamically loads standard-models based on the client request.

A thread lock is used, to make model prediction thread safe. But this also means that connections have to wait, if another connection currently predicts.

### Motivation

I use a large-v3 tensorrt model. It would take 5secs to load for every new client connection. With the single model option, this is reduced to <1sec. Also, I only want to have the model in VRAM once.

### CODE REVIEW

**Comment by makaveli10** [comment]
@peldszus Thanks for putting this together.
I think it would be useful to make the single model mode as the default model?

**Comment by peldszus** [comment]
> I think it would be useful to make the single model mode as the default model?

It probably depends on your intended audience, but I agree.

For private users with no, or just one GPU, single model mode is probably the best option.

In production environments with higher throughput, maybe with multiple GPUs on one node, there are different scaling / optimizations routes to go, but they could involve single model mode as well.

**Comment by peldszus** [comment]
@makaveli10 If this is fine for you, I can adjust the argument parser and the readme.

**Comment by peldszus** [comment]
@makaveli10 Have a look now, I updated the option defaultness and the readme correspondingly.

**Comment by makaveli10** [comment]
Looks good to me. I would add an option to use single model if not using a custom model as well but I guess for a future realease because that is a bit more complicated in terms of maintaining a dict of models with model_sizes that have been instantiated and clearing it up if no client is using that model size.

**Pull request merged**
