### PR TITLE
feat: Add the `large-v3` model

### PR DESCRIPTION
**Pull request by hcljsq**
Add Whisper's latest model.

### CODE REVIEW

**Review by zoq — APPROVED** [review]
Looks good to me, thanks for the contribution.

**Comment by hcljsq** [comment]
I also updated the `faster-whisper` version to `0.10.0`, because `faster-whisper` also constrained the version range of the Whisper model.

**Review by makaveli10 — CHANGES_REQUESTED** [review]
Hello, thanks for the PR. Large-v3 expects 128 mel filters instead of 80. So, we need to update the transcriber as well. Its mostly same as the `transcribe.py` in faster-whisper except for a few changes i.e. language detection once and return segments instead of yield, we will remove this dependency of updating transcriber in upcoming release but for now I think we should update `transcriber.py` as well based on the faster-whisper update to support `large-v3`. If you can incorporate the below changes that would be great.

- https://github.com/collabora/WhisperLive/blob/5918b5ed4247a7c82050c6aa5a2ae88f1463278f/whisper_live/transcriber.py#L7
```python
import json
from inspect import signature
```

- https://github.com/collabora/WhisperLive/blob/5918b5ed4247a7c82050c6aa5a2ae88f1463278f/whisper_live/transcriber.py#L147
```python
self.feat_kwargs = self._get_feature_kwargs(model_path)
self.feature_extractor = FeatureExtractor(**self.feat_kwargs)
```

- https://github.com/collabora/WhisperLive/blob/5918b5ed4247a7c82050c6aa5a2ae88f1463278f/whisper_live/transcriber.py#L163
```python
def _get_feature_kwargs(self, model_path) -> dict:
    preprocessor_config_file = os.path.join(model_path, "preprocessor_config.json")
    config = {}
    if os.path.isfile(preprocessor_config_file):
        try:
            with open(preprocessor_config_file, "r", encoding="utf-8") as json_file:
                config = json.load(json_file)
            valid_keys = signature(FeatureExtractor.__init__).parameters.keys()
            config = {k: v for k, v in config.items() if k in valid_keys}
        except json.JSONDecodeError as e:
            self.logger.warning(
                "Could not load preprocessor_config.json: %s", str(e)
            )

    return config
```

**Comment by hcljsq** [comment]
I've updated the `transcriber.py` as per your suggestions to support the large-v3 model with 128 mel filters. Please let me know if there are any further changes needed.

**Review by makaveli10 — APPROVED** [review]
Thanks for the quick update.

**Pull request merged**
